sugar_files(SOURCE_FILES
        config.hpp
        error.cpp
        error.hpp
        program.cpp
        program.hpp
        resource.cpp
        resource.hpp
        shader.cpp
        shader.hpp)
